const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx=vm.createContext({React:{createElement:(type,props,...children)=>({type,props,children})},DCLogic:class{setState(p){Object.assign(this.state,typeof p==='function'?p(this.state):p)}},window:{}});
vm.runInContext(fs.readFileSync('public/app.js','utf8')+';globalThis.App=Component;',ctx);
const text=n=>n==null?'':typeof n==='string'?n:Array.isArray(n)?n.map(text).join(' '):text(n.children);
(async()=>{
  const app=new ctx.App(),calls=[];
  app.state.data={CATEGORIES:[],SUBCATEGORIES:[],BRANDS:[]};
  app.state.categoriesLocal=[];
  app.toast=()=>{};
  app.reloadCatalog=async()=>{};
  app.authPost=async(url,body,method)=>{
    calls.push({url,body,method});
    return url==='/api/categories'?{category:{...body}}:{record:{...body,id:calls.length}};
  };
  app.openCategoryModal();
  assert(text(app.buildCategoryModal()).includes('Step 1 of 3'));
  await app.saveCategory();assert.strictEqual(calls.length,0);
  app.state.categoryForm={name:'Appliances',classification:'Non-Perishable',status:'Active'};
  await app.saveCategory();
  assert.strictEqual(app.state.categoryStep,'subcategory');assert(app.state.categoryModalOpen);
  assert(text(app.buildCategoryModal()).includes('Category: Appliances'));
  await app.saveCategory();assert.strictEqual(calls.length,1);
  app.state.categorySetupName='Refrigerators';
  const post=app.authPost;
  app.authPost=async()=>{throw new Error('Please retry');};
  await app.saveCategory();
  assert.strictEqual(app.state.categoryStep,'subcategory');assert.strictEqual(app.state.categorySetupName,'Refrigerators');
  assert.strictEqual(app.state.categoryError,'Please retry');
  app.authPost=post;
  await app.saveCategory();
  assert.strictEqual(calls[1].body.category,'Appliances');assert.strictEqual(app.state.categoryStep,'brand');
  assert(text(app.buildCategoryModal()).includes('Subcategory: Refrigerators'));
  app.state.categorySetupName='Samsung';
  await app.saveCategory();
  assert.strictEqual(calls[2].url,'/api/product-master/brands');assert(!app.state.categoryModalOpen);
  assert.strictEqual(app.state.regCategory,'Appliances');assert.strictEqual(app.state.regSubcategoryId,2);assert.strictEqual(app.state.regBrandId,3);
  app.state.categoryStep='brand';app.state.categoryModalOpen=true;app.state.categorySetupBrandId='3';
  await app.saveCategory();assert.strictEqual(calls.length,3,'Existing brands are reused');
  app.openCategoryModal();assert.strictEqual(app.state.categoryStep,'category');assert.strictEqual(app.state.categorySetupBrandId,'');
  app.editCategory({name:'Appliances',classification:'Non-Perishable'})();
  app.authPost=async()=>({category:{name:'Appliances',classification:'Non-Perishable'}});
  await app.saveCategory();assert(!app.state.categoryModalOpen,'Editing does not start setup');
  console.log('Sequential category setup passed: validation, category linkage, failure/retry, brand creation/reuse and editing.');
})().catch(error=>{console.error(error);process.exitCode=1;});
