const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx=vm.createContext({React:{createElement:(type,props,...children)=>({type,props,children})},DCLogic:class{setState(p){Object.assign(this.state,typeof p==='function'?p(this.state):p)}},window:{}});
vm.runInContext(fs.readFileSync('public/app.js','utf8')+';globalThis.App=Component;',ctx);
const text=n=>n==null?'':typeof n==='string'?n:Array.isArray(n)?n.map(text).join(' '):text(n.children);
(async()=>{
  const app=new ctx.App(),calls=[];
  app.state.data={CATEGORIES:[],SUBCATEGORIES:[],BRANDS:[]};
  app.state.categoriesLocal=[];
  app.toast=()=>{};
  app.reloadCatalog=async()=>{};
  app.authPost=async(url,body,method)=>{
    calls.push({url,body,method});
    return url==='/api/categories'?{category:{...body}}:{record:{...body,id:calls.length}};
  };
  app.openCategoryModal();
  assert(text(app.buildCategoryModal()).includes('Step 1 of 3'));
  await app.saveCategory();assert.strictEqual(calls.length,0);
  app.state.categoryForm={name:'Appliances',classification:'Non-Perishable',status:'Active'};
  await app.saveCategory();
  assert.strictEqual(app.state.categoryStep,'subcategory');assert(app.state.categoryModalOpen);
  assert(text(app.buildCategoryModal()).includes('Category: Appliances'));
  await app.saveCategory();assert.strictEqual(calls.length,1);
  app.state.categorySetupName='Refrigerators';
  const post=app.authPost;
  app.authPost=async()=>{throw new Error('Please retry');};
  await app.saveCategory();
  assert.strictEqual(app.state.categoryStep,'subcategory');assert.strictEqual(app.state.categorySetupName,'Refrigerators');
  assert.strictEqual(app.state.categoryError,'Please retry');
  app.authPost=post;
  await app.saveCategory();
  assert.strictEqual(calls[1].body.category,'Appliances');assert.strictEqual(app.state.categoryStep,'brand');
  assert(text(app.buildCategoryModal()).includes('Subcategory: Refrigerators'));
  app.state.categorySetupName='Samsung';
  await app.saveCategory();
  assert.strictEqual(calls[2].url,'/api/product-master/brands');assert(!app.state.categoryModalOpen);
  assert.strictEqual(app.state.regCategory,'Appliances');assert.strictEqual(app.state.regSubcategoryId,2);assert.strictEqual(app.state.regBrandId,3);
  app.state.categoryStep='brand';app.state.categoryModalOpen=true;app.state.categorySetupBrandId='3';
  await app.saveCategory();assert.strictEqual(calls.length,3,'Existing brands are reused');
  app.openCategoryModal();assert.strictEqual(app.state.categoryStep,'category');assert.strictEqual(app.state.categorySetupBrandId,'');
  app.editCategory({name:'Appliances',classification:'Non-Perishable'})();
  app.authPost=async()=>({category:{name:'Appliances',classification:'Non-Perishable'}});
  await app.saveCategory();assert(!app.state.categoryModalOpen,'Editing does not start setup');
  app.openCategoryModal();
  app.authPost=async(url,body,method)=>{
    calls.push({url,body,method});
    return url.startsWith('/api/categories')?{category:{...body}}:{record:{...body,id:11}};
  };
  app.state.categoryForm={name:'Electronics',classification:'Non-Perishable',status:'Active'};
  await app.saveCategory();
  app.state.categorySetupName='Phones';
  await app.saveCategory();
  app.state.categorySetupName='New Brand';
  assert(text(app.buildCategoryModal()).includes('Previous'));
  assert(text(app.buildCategoryModal()).includes('Cancel'));
  app.previousCategoryStep();
  assert.strictEqual(app.state.categorySetupName,'Phones');
  app.state.categorySetupName='Mobile Phones';
  app.previousCategoryStep();
  assert.strictEqual(app.state.categoryStep,'category');
  app.state.categoryForm.name='Devices';
  await app.saveCategory();
  assert.strictEqual(calls.at(-1).url,'/api/categories/Electronics');
  assert.strictEqual(calls.at(-1).method,'PATCH');
  assert.strictEqual(app.state.categorySetupName,'Mobile Phones');
  await app.saveCategory();
  assert.strictEqual(calls.at(-1).url,'/api/product-master/subcategories/11');
  assert.strictEqual(calls.at(-1).method,'PATCH');
  assert.strictEqual(calls.at(-1).body.category,'Devices');
  assert.strictEqual(app.state.categorySetupName,'New Brand');
  assert.strictEqual(app.state.data.SUBCATEGORIES.filter(r=>r.id===11).length,1);
  app.state.categorySetupName='';app.state.categorySetupBrandId='3';
  app.previousCategoryStep();await app.saveCategory();
  assert.strictEqual(app.state.categorySetupBrandId,'3','Existing brand choice survives Previous');
  const count=calls.length;
  app.categoryBusy=true;app.previousCategoryStep();app.closeCategoryModal();
  assert.strictEqual(app.state.categoryStep,'brand');assert(app.state.categoryModalOpen);
  app.categoryBusy=false;app.closeCategoryModal();
  assert(!app.state.categoryModalOpen);assert.strictEqual(calls.length,count,'Cancel does not save changes');
  app.openCategoryModal();assert.strictEqual(app.state.categorySetupSubcategory,null);assert.strictEqual(app.state.categorySetupBrandDraft,'');
  console.log('Previous preserves drafts, updates existing records, blocks during saves, and Cancel closes without saving.');
  console.log('Sequential category setup passed: validation, category linkage, failure/retry, brand creation/reuse and editing.');
})().catch(error=>{console.error(error);process.exitCode=1;});
